import type { Translation } from './bg';
// Provisional editorial copy. Owner approval pending.
export const en: Translation = {
  nav: { home: 'Home', accommodation: 'Accommodation', gallery: 'Gallery', location: 'Location', contact: 'Contact' },
  meta: {
    home: { title: 'The Nest | Bungalows in Lozenets, Bulgaria', description: 'Small bungalows surrounded by greenery in Lozenets, on Bulgaria’s southern Black Sea coast. Discover the atmosphere and accommodation at The Nest.' },
    accommodation: { title: 'Accommodation | The Nest, Lozenets', description: 'Discover small bungalow accommodation among greenery at The Nest in Lozenets, Bulgaria, near the Black Sea.' },
    gallery: { title: 'Gallery | The Nest, Lozenets', description: 'A visual introduction to the bungalows, greenery and outdoor spaces at The Nest in Lozenets.' },
    location: { title: 'Location | The Nest, Lozenets, Bulgaria', description: 'Find out about Lozenets, near Tsarevo on Bulgaria’s southern Black Sea coast, home to The Nest bungalow accommodation.' },
    contact: { title: 'Contact and enquiries | The Nest, Lozenets', description: 'Contact and accommodation enquiry information for The Nest in Lozenets, Bulgaria.' },
  },
  ui: { menu: 'Menu', close: 'Close', skip: 'Skip to content', explore: 'Explore the bungalows', gallery: 'View the gallery', location: 'Discover Lozenets', contact: 'Contact and enquiries', enquire: 'Make an enquiry', back: 'Back to home', next: 'Next image', previous: 'Previous image', enlarge: 'View image', all: 'All', illustration: 'Atmosphere illustration, not a property photograph.', photoPending: 'Original photographs coming soon.', image: 'Image', of: 'of', address: 'Address', arrival: 'Getting here', parking: 'Parking', beach: 'The beach', maps: 'Open in Google Maps', guests: 'Guests', bedrooms: 'Bedrooms', bathrooms: 'Bathrooms', beds: 'Beds', amenities: 'Amenities', details: 'Your stay', reviews: 'Words from our guests' },
  home: {
    eyebrow: 'LOZENETS, BULGARIA', title: 'Your quiet place by the sea.', subtitle: 'Small bungalows. Plenty of greenery. Summer at your own pace.',
    introLabel: 'WELCOME TO THE NEST', introTitle: 'Closer to nature. Closer to each other.', introBody: 'Some places make summer feel simpler. The Nest is a small place to stay among the greenery of Lozenets, close to the sea. For the days when all you need is a little quiet and your favourite people.',
    stayLabel: 'ACCOMMODATION', stayTitle: 'A little place. A feeling of your own.', stayBody: 'Bungalows among greenery and room for outdoor living. Discover a more easygoing side of summer in Lozenets.',
    atmosphereLabel: 'SUMMER AT THE NEST', atmosphereTitle: 'Let the day unfold.', atmosphereBody: 'Greenery all around. A veranda for the slower moments. The sea nearby. The little things we love about summer.',
    galleryLabel: 'THE ATMOSPHERE', galleryTitle: 'A little feeling of summer.',
    locationLabel: 'SOUTH, BY THE SEA', locationTitle: 'Lozenets. Where summer finds you.', locationBody: 'On Bulgaria’s southern Black Sea coast, close to Tsarevo. A small seaside village, greenery and the Black Sea. This is where you’ll find The Nest.',
    finalTitle: 'Your next summer, in Lozenets.', finalBody: 'Get to know the place. Picture your days by the sea.',
  },
  accommodation: { label: 'YOUR STAY', title: 'Your little corner of green.', lead: 'The independent spirit of a bungalow. The easy feeling of summer.', title2: 'Room to slow down.', body: 'The Nest brings together small bungalows in the greenery of Lozenets. Verandas and outdoor living are part of the feeling of the place.', pending: 'Bungalow details and original photographs will be added soon.', policies: 'Before you arrive' },
  gallery: { label: 'GALLERY', title: 'Greenery. Light. Summer.', lead: 'A small glimpse into the real atmosphere of The Nest.', notice: 'Photographs of the bungalows, greenery and spaces for time outdoors.', categories: { exterior: 'Bungalows', entrance: 'Entrance', shared: 'Outdoors' }, empty: 'We’re preparing more photographs of The Nest.' },
  location: { label: 'LOCATION', title: 'Head south. Find Lozenets.', lead: 'Your direction: the Bulgarian Black Sea coast, close to Tsarevo.', title2: 'The sea is part of the story.', body: 'The Nest is at 12 Osogovo Street in Lozenets. Published descriptions place Small Beach and Hacienda about 200 m away, while the surrounding greenery helps soften village-street noise.', travelTitle: 'Before you set off', travelBody: 'The address appears on Booking.com and local directories. We will add a precise route and map pin after the hosts confirm them.', region: 'Lozenets and Tsarevo', regionBody: 'Two names to begin your summer on the southern Black Sea coast.', diagram: 'A schematic guide to the area, without the exact position of The Nest.' },
  contact: { label: 'CONTACT', title: 'Let’s start with a hello.', lead: 'For summer plans, your stay, and the little questions before you travel.', title2: 'Get in touch with The Nest', pending: 'We’re preparing the details for contacting the hosts directly. You’ll find the confirmed ways to enquire here as soon as they’re ready.', ready: 'Contact the hosts about dates, arrangements and anything you would like to know about your stay.', note: 'An enquiry is not a confirmed booking. Dates and arrangements are agreed directly with the hosts.', planTitle: 'While you plan your summer', planBody: 'Explore the place and get to know Lozenets.', channels: { phone: 'Phone', email: 'Email', whatsapp: 'WhatsApp', viber: 'Viber', messenger: 'Messenger', facebook: 'Facebook', bookingCom: 'Booking.com', airbnb: 'Airbnb' } },
  footer: { line: 'A little place for your summer.', region: 'Lozenets, Bulgaria', copyright: 'All rights reserved.', privacy: 'Privacy' },
  notFound: { title: 'This path leads nowhere.', text: 'We couldn’t find that page. Let’s take you back to The Nest.' },
};
